version: '3.4'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
     - 2181:2181
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  myapp:
    build: .
    ports: 
      - 8080:8080
    depends_on: 
      - kafka
    environment: 
      - KAFKA_URL=kafka:9092
      - KAFKA_TOPIC=user-topic